import type { ReactNode } from 'react';
import { BearIcons } from '@forgedevstack/bear';
import { GROUP_ORDER } from '@forgedevstack/aerocraft';
import {
  AlignContentPage,
  AlignItemsPage,
  AlignSelfPage,
  FlexBasisPage,
  FlexDirectionPage,
  FlexGrowPage,
  FlexPage,
  FlexShrinkPage,
  FlexWrapPage,
  GapPage,
  GridAutoColumnsPage,
  GridAutoFlowPage,
  GridAutoRowsPage,
  GridColumnPage,
  GridRowPage,
  GridTemplateColumnsPage,
  GridTemplateRowsPage,
  HeightPage,
  JustifyContentPage,
  JustifyItemsPage,
  JustifySelfPage,
  MaxHeightPage,
  MaxWidthPage,
  MinHeightPage,
  MinWidthPage,
  OrderPage,
  PlaceContentPage,
  PlaceItemsPage,
  PlaceSelfPage,
  ReferenceHubPage,
  SizePage,
  WidthPage,
} from '../Reference';

export const REFERENCE_ROUTES: Record<string, () => JSX.Element> = {
  reference: () => <ReferenceHubPage />,
  'reference/flex': () => <FlexPage />,
  'reference/flex-direction': () => <FlexDirectionPage />,
  'reference/flex-wrap': () => <FlexWrapPage />,
  'reference/flex-basis': () => <FlexBasisPage />,
  'reference/flex-grow': () => <FlexGrowPage />,
  'reference/flex-shrink': () => <FlexShrinkPage />,
  'reference/order': () => <OrderPage />,
  'reference/justify-content': () => <JustifyContentPage />,
  'reference/align-items': () => <AlignItemsPage />,
  'reference/align-self': () => <AlignSelfPage />,
  'reference/align-content': () => <AlignContentPage />,
  'reference/gap': () => <GapPage />,
  'reference/grid-template-columns': () => <GridTemplateColumnsPage />,
  'reference/grid-column': () => <GridColumnPage />,
  'reference/grid-template-rows': () => <GridTemplateRowsPage />,
  'reference/grid-row': () => <GridRowPage />,
  'reference/grid-auto-flow': () => <GridAutoFlowPage />,
  'reference/grid-auto-columns': () => <GridAutoColumnsPage />,
  'reference/grid-auto-rows': () => <GridAutoRowsPage />,
  'reference/justify-items': () => <JustifyItemsPage />,
  'reference/justify-self': () => <JustifySelfPage />,
  'reference/place-content': () => <PlaceContentPage />,
  'reference/place-items': () => <PlaceItemsPage />,
  'reference/place-self': () => <PlaceSelfPage />,
  'reference/width': () => <WidthPage />,
  'reference/min-width': () => <MinWidthPage />,
  'reference/max-width': () => <MaxWidthPage />,
  'reference/height': () => <HeightPage />,
  'reference/min-height': () => <MinHeightPage />,
  'reference/max-height': () => <MaxHeightPage />,
  'reference/size': () => <SizePage />,
};

export const GROUP_ICON: Record<string, ReactNode> = {
  flex: <BearIcons.GridViewIcon size="xs" />,
  grid: <BearIcons.GridIcon size="xs" />,
  position: <BearIcons.MapPinIcon size="xs" />,
  size: <BearIcons.MaximizeIcon size="xs" />,
  spacing: <BearIcons.BoxIcon size="xs" />,
  gap: <BearIcons.HoneycombIcon size="xs" />,
  text: <BearIcons.TextFieldsIcon size="xs" />,
  display: <BearIcons.LayersIcon size="xs" />,
  overflow: <BearIcons.UnfoldMoreIcon size="xs" />,
  cursor: <BearIcons.MouseIcon size="xs" />,
  transition: <BearIcons.ZapIcon size="xs" />,
  interactive: <BearIcons.DragHandleIcon size="xs" />,
};

export function isGroupSlug(s: string | undefined): s is (typeof GROUP_ORDER)[number] {
  return !!s && (GROUP_ORDER as readonly string[]).includes(s);
}
