export const DOC_TOPIC_CATEGORIES = [
  {
    id: 'layout',
    path: 'layout',
    properties: [
      'aspect-ratio',
      'columns',
      'break-after',
      'break-before',
      'break-inside',
      'box-decoration-break',
      'box-sizing',
      'display',
      'float',
      'clear',
      'isolation',
      'object-fit',
      'object-position',
      'overflow',
      'overscroll-behavior',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'visibility',
      'z-index',
    ],
  },
  {
    id: 'flexbox-grid',
    path: 'flexbox-grid',
    properties: [
      'flex-basis',
      'flex-direction',
      'flex-wrap',
      'flex',
      'flex-grow',
      'flex-shrink',
      'order',
      'grid-template-columns',
      'grid-column',
      'grid-template-rows',
      'grid-row',
      'grid-auto-flow',
      'grid-auto-columns',
      'grid-auto-rows',
      'gap',
      'justify-content',
      'justify-items',
      'justify-self',
      'align-content',
      'align-items',
      'align-self',
      'place-content',
      'place-items',
      'place-self',
    ],
  },
  {
    id: 'spacing',
    path: 'spacing',
    properties: ['padding', 'margin'],
  },
  {
    id: 'sizing',
    path: 'sizing',
    properties: [
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'inline-size',
      'min-inline-size',
      'max-inline-size',
      'block-size',
      'min-block-size',
      'max-block-size',
    ],
  },
  {
    id: 'typography',
    path: 'typography',
    properties: [
      'font-family',
      'font-size',
      'font-smoothing',
      'font-style',
      'font-weight',
      'font-stretch',
      'font-variant-numeric',
      'font-feature-settings',
      'letter-spacing',
      'line-clamp',
      'line-height',
      'list-style-image',
      'list-style-position',
      'list-style-type',
      'text-align',
      'color',
      'text-decoration-line',
      'text-decoration-color',
      'text-decoration-style',
      'text-decoration-thickness',
      'text-underline-offset',
      'text-transform',
      'text-overflow',
      'text-wrap',
      'text-indent',
      'vertical-align',
      'white-space',
      'word-break',
      'overflow-wrap',
      'hyphens',
      'content',
    ],
  },
  {
    id: 'backgrounds',
    path: 'backgrounds',
    properties: [
      'background-attachment',
      'background-clip',
      'background-color',
      'background-image',
      'background-origin',
      'background-position',
      'background-repeat',
      'background-size',
    ],
  },
  {
    id: 'borders',
    path: 'borders',
    properties: [
      'border-radius',
      'border-width',
      'border-color',
      'border-style',
      'outline-width',
      'outline-color',
      'outline-style',
      'outline-offset',
    ],
  },
  {
    id: 'effects',
    path: 'effects',
    properties: [
      'box-shadow',
      'text-shadow',
      'opacity',
      'mix-blend-mode',
      'background-blend-mode',
      'mask-clip',
      'mask-composite',
      'mask-image',
      'mask-mode',
      'mask-origin',
      'mask-position',
      'mask-repeat',
      'mask-size',
      'mask-type',
    ],
  },
  {
    id: 'filters',
    path: 'filters',
    properties: [
      'filter',
      'blur',
      'brightness',
      'contrast',
      'drop-shadow',
      'grayscale',
      'hue-rotate',
      'invert',
      'saturate',
      'sepia',
      'backdrop-filter',
      'backdrop-blur',
      'backdrop-brightness',
      'backdrop-contrast',
      'backdrop-grayscale',
      'backdrop-hue-rotate',
      'backdrop-invert',
      'backdrop-opacity',
      'backdrop-saturate',
      'backdrop-sepia',
    ],
  },
  {
    id: 'tables',
    path: 'tables',
    properties: ['border-collapse', 'border-spacing', 'table-layout', 'caption-side'],
  },
  {
    id: 'transitions-animation',
    path: 'transitions-animation',
    properties: [
      'transition-property',
      'transition-behavior',
      'transition-duration',
      'transition-timing-function',
      'transition-delay',
      'animation',
    ],
  },
  {
    id: 'transforms',
    path: 'transforms',
    properties: [
      'backface-visibility',
      'perspective',
      'perspective-origin',
      'rotate',
      'scale',
      'skew',
      'transform',
      'transform-origin',
      'transform-style',
      'translate',
    ],
  },
  {
    id: 'interactivity',
    path: 'interactivity',
    properties: [
      'accent-color',
      'appearance',
      'caret-color',
      'color-scheme',
      'cursor',
      'field-sizing',
      'pointer-events',
      'resize',
      'scroll-behavior',
      'scroll-margin',
      'scroll-padding',
      'scroll-snap-align',
      'scroll-snap-stop',
      'scroll-snap-type',
      'touch-action',
      'user-select',
      'will-change',
    ],
  },
  {
    id: 'svg',
    path: 'svg',
    properties: ['fill', 'stroke', 'stroke-width'],
  },
  {
    id: 'accessibility',
    path: 'accessibility',
    properties: ['forced-color-adjust'],
  },
] as const;

export type DocTopicCategoryId = (typeof DOC_TOPIC_CATEGORIES)[number]['id'];

export function findTopicProperty(
  categoryPath: string,
  propertySlug: string,
): string | undefined {
  const cat = DOC_TOPIC_CATEGORIES.find((c) => c.path === categoryPath);
  if (!cat) return undefined;
  const hit = cat.properties.find((p) => p === propertySlug);
  return hit;
}

export function isTopicDocPath(docPath: string): boolean {
  const parts = docPath.split('/').filter(Boolean);
  if (parts.length !== 2) return false;
  return findTopicProperty(parts[0], parts[1]) !== undefined;
}
